---
title: EnemyFSM
---
stateDiagram-v2
    [*] --> static

    static --> normal : raise_to_normal
    normal --> high   : raise_to_high
    high   --> normal : lower_to_normal

    note right of static
        Enemies will remain static until radius overlaps their vision radius
    end note

    note right of high
        first levels will only have it as normal,
        then after some levels, depending on the enemy, it will shift to high

    end note